### ISSUE TITLE
recommendation for code structure

### ISSUE THREAD

**Issue by 18062706139fcz** [Ki-Wi-Berry/bilibili-videos#1]
1. store.js in src is better than outside
2. router.js should have a folder outside like this:
- router
   - index.js  

and i think u can seperate frontend from back-end, which can make code reader easiler to run and read

**Comment by Ki-Wi-Berry** [comment]
Thanks for the advice, this is the first time someone has given me an issue hhh,
There are too many references involved in changing the location of the file, so I will not change it this time, but I will take care of it next time, thanks again for the suggestion
